---   
- name: Get users Json content
  set_fact:
    jsoncontent: "{{ lookup('file',cloud_nas_set_users_configurationfile) | from_json }}"
  no_log: True

- name: Loop over jsoncontent for normal users creation/edition
  include_tasks: create_normal_user.yml
  loop: "{{ jsoncontent.users }}"
  no_log: True

- name: Create samba users
  shell: "(echo {{ item['smbpasswd'] }}; echo {{ item['smbpasswd'] }}) | smbpasswd -s -a {{ item['name'] }}"
  with_items:
    - "{{cloud_nas_samba_users}}"
  no_log: True
    
- name: FTP group for anonymous access
  ansible.builtin.group:
    name: "{{ cloud_nas_ftp_anonymous_group }}"
    state: present

- name: FTP user for anonymous access
  user:
    comment: "Anonymous ProFTPD user"
    group: "{{ cloud_nas_ftp_anonymous_group }}"
    create_home: no
    home: "{{ cloud_nas_public_folder }}"
    name : "{{ cloud_nas_ftp_anonymous_user }}"
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation') | password_hash('sha512') }}"
    update_password: "always"
    shell: /bin/sh
