- name: Install packages for FILESERVER features
  ansible.builtin.include_tasks: install_packages.yml
  loop: "{{ cloud_nas_fileserver_required_packages }}"

- name: Ensure ftp folders root permissions are set correctly
  file:
    path: "{{cloud_nas_ftp_folders_root}}"
    state: directory
    owner: root
    group: users
    mode: "{{ cloud_nas_ftp_folders_root_permissions }}"

- name: Create private root folder
  file:
    path: "{{cloud_nas_private_folders.root}}"
    state: directory
    owner: root
    group: "{{cloud_nas_root_folders_group}}"
    mode: "{{cloud_nas_root_folders_mode}}"

- name: Create private folders for users
  file:
    path: "{{cloud_nas_private_folders.root}}/{{item.name}}"
    state: directory
    owner: "{{item.name}}"
    group: root
    mode: u=rwx,g-rwx,o-rwx
    recurse: yes
    follow: false
  with_items:
    - "{{cloud_nas_samba_users}}"
  no_log: "{{ no_debug }}"

- name: Create shared folders
  file:
    path: "{{item.path}}"
    state: directory
    mode: "{{item.mode}}"
    group: "{{ cloud_nas_shared_folders_group }}"
    recurse: yes
  with_items:
    - "{{cloud_nas_shared_folders}}"

- name: Create sftp authorized keys directory
  file:
    path: /etc/proftpd/authorized_keys
    state: directory
    mode: u=rwx,g=rx,o=rx

- name: FTP group for anonymous access
  ansible.builtin.group:
    name: "{{ cloud_nas_ftp_anonymous_group }}"
    state: present

- name: FTP user for anonymous access
  user:
    comment: "Anonymous ProFTPD user"
    group: "{{ cloud_nas_ftp_anonymous_group }}"
    create_home: no
    home: "{{ cloud_nas_public_folder }}"
    name : "{{ cloud_nas_ftp_anonymous_user }}"
    password: "{{ lookup('password', '/dev/null chars=ascii_letters,digits,punctuation') | password_hash('sha512') }}"
    update_password: "always"
    shell: /bin/sh
  
- name: Copy sftp authorized public keys for users
  copy: src={{item}} dest=/etc/proftpd/authorized_keys mode=0644
  with_fileglob: "{{ cloud_nas_authorized_keys_dir }}/*"

- name: Ensure proftpd is running
  service: name=proftpd state=started

- name: Edit ProFtpd Sftp module configuration
  template:
    src: proftpd/cloud-nas_sftp.conf
    dest: /etc/proftpd/sftp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd
  
- name: Edit ProFtpd modules configuration
  template:
    src: proftpd/cloud-nas_modules.conf
    dest: /etc/proftpd/modules.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd

- name: Edit ProFtpd main configuration
  template:
    src: proftpd/cloud-nas_proftpd.conf
    dest: /etc/proftpd/proftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd
