---
# tasks file for cloud-nas

- name: Install packages for NAS features
  ansible.builtin.include_tasks: common.yml

- name: Install packages for NAS features
  ansible.builtin.include_tasks: mediacenter.yml
  when: cloud_nas_mediacenter_enabled

- name: Install packages for NAS features
  ansible.builtin.include_tasks: fileserver.yml
  when: cloud_nas_fileserver_enabled
