---
# tasks file for cloud-nas

- name: Install cloud-nas packages
  import_tasks: install_pkgs.yml
  
- name: Start samba service, if not started
  ansible.builtin.service:
    name: smbd
    state: started

- name: Create normal users, Ftp and Samba users
  import_tasks: create_users.yml

- name: Create folders
  import_tasks: create_folders.yml

- name: Edit Samba configuration
  template:
    src: samba/cloud-nas_smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart smbd
  
- name: Copy sftp authorized public keys for users
  copy: src={{item}} dest=/etc/proftpd/authorized_keys mode=0644
  with_fileglob: "{{ cloud_nas_authorized_keys_dir }}/*"

- name: Ensure proftpd is running
  service: name=proftpd state=started

- name: Edit ProFtpd Sftp module configuration
  template:
    src: proftpd/cloud-nas_sftp.conf
    dest: /etc/proftpd/sftp.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd
  
- name: Edit ProFtpd modules configuration
  template:
    src: proftpd/cloud-nas_modules.conf
    dest: /etc/proftpd/modules.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd

- name: Edit ProFtpd main configuration
  template:
    src: proftpd/cloud-nas_proftpd.conf
    dest: /etc/proftpd/proftpd.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - restart proftpd
